//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int UserId { get; set; }
        public double TotalPrice { get; set; }
        public int StoreId { get; set; }
        public string Address { get; set; }
        public string Landmark { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public int StatusTypeId { get; set; }
        public string Comments { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string TimeSlot { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedByUserId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> DeliveryAgentId { get; set; }
    }
}
