//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public string FileExtension { get; set; }
        public string Address { get; set; }
        public string Landmark { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public bool IsActive { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedByUserId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
