INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanViewUsers',  'CanViewUsers', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanManageUsers',  'CanManageUsers', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanViewRoles',  'CanViewRoles', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanManageRoles',  'CanManageRoles', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanViewOrders',  'CanViewOrders', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanAssignOrders',  'CanAssignOrders', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanMakeOrderDelivered',  'CanMakeOrderDelivered', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanViewStores',  'CanViewStores', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanViewProducts',  'CanViewProducts', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanViewGeoLocations',  'CanViewGeoLocations', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanManageGeoLocations',  'CanManageGeoLocations', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanManageStores',  'CanManageStores', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanManageProducts',  'CanManageProducts', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanCancelOrder',  'CanCancelOrder', 1, 1, GETDATE(), 1, GETDATE())
INSERT INTO dbo.ActivityRight (Name, [Desc], IsActive, CreatedByUserId,  CreatedDate, UpdatedByUserId, UpdatedDate)
					  VALUES  ('CanUpdateBulkProdutc',  'CanUpdateBulkProdutc', 1, 1, GETDATE(), 1, GETDATE())
 